
paths:
  train_data:   "data/train.csv"
  test_data:    "data/test.csv"
  raw_data:     "data/mock_loki_logs.csv"
  models_dir:   "models"
  metrics_file: "metrics.json"
  plots_dir:    "plots"


mlflow:
  tracking_uri:  "./mlruns"
  artifact_path: "loki_pipeline_model"

api:
  host: "0.0.0.0"
  port: 8000

monitoring:
  reference_data:  "data/train.csv"
  production_data: "data/production.csv"
